code/WebApp/Pages/Index.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.AspNetCore.Mvc.RazorPages;
using reCAPTCHA.AspNetCore;
using WebApp.models;
using WebApp.services;

namespace WebApp.Pages
{
    public class IndexModel : PageModel
    {
        private readonly IMessageService _messageService;
        private readonly IRecaptchaService _recaptchaService;

        public Message Message { get; set; } = new Message();
        public string Status { get; set; }

        [BindProperty]
        public string Text { get; set; }

        public IndexModel(IMessageService messageService, IRecaptchaService recaptchaService)
        {
            _recaptchaService = recaptchaService;
            _messageService = messageService;
        }

        public async Task OnPageHandlerSelectionAsync(HttpContext httpContext)
        {
            if (httpContext.Request.Method == "POST")
            {
                var response = await _recaptchaService.Validate(httpContext.Request);

                if (!response.success) throw new System.Exception("There was an error validating the google recaptcha response. Please try again, or contact the site owner.");
            }
        }

        public override async Task OnPageHandlerSelectionAsync(PageHandlerSelectedContext context)
        {
            await OnPageHandlerSelectionAsync(context.HttpContext);
        }

        public override void OnPageHandlerExecuted(PageHandlerExecutedContext _)
        {
            Text = string.Empty;

            ModelState.Clear();
        }

        public void OnPostIsSpam()
        {
            Status = "- Checked text";

            Message = new Message
            {
                IsSpam = _messageService.IsSpam(Text),
                Text = Text
            };
        }

        public async Task OnPostAddSpam()
        {
            Status = "- Added spam message";

            await _messageService.AddSpam(Text);

            Message = new Message
            {
                IsSpam = true,
                Text = Text
            };
        }
    }
}

code/WebApp/Pages/Index.cshtml
@page
@using reCAPTCHA.AspNetCore
@using reCAPTCHA.AspNetCore.Versions
@using Microsoft.Extensions.Options
@model IndexModel
@inject IOptions<RecaptchaSettings> RecaptchaSettings;
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<div class="container">
    <h2>Spam or not spam, that's the question</h2>
    
        <div class="card">
            <div class="card-body">
                <h3 class="card-title">Result @Model.Status</h3>
        
                <p class="card-text">@(Model.Message.IsSpam ? "Spam" : "Not spam")</p>
                <p class="card-text">@Model.Message.Text</p>
            </div>
        </div>

        <br /><br />
        <br /><br /> 

        <form method="post"> 
            <div class="card">
                <div class="card-body">
                    <h3 class="card-title" >Message</h3>

                    <div class="form-group row">
                      <label>Message to validate or add</label>
                      <textarea  class="form-control" asp-for="Text" placeholder="Enter message to validate/add"></textarea>
                    </div>

                        <div class="form-group">
                            @(Html.Recaptcha<RecaptchaV2Checkbox>(RecaptchaSettings.Value))
                        </div>

                    <button asp-page-handler="IsSpam" type="submit" class="btn btn-primary">Check message</button>
                    <button asp-page-handler="AddSpam" type="submit" class="btn btn-primary">Add spam message</button>
                </div>
            </div>
        </form>
</div>

code/WebApp/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Spam or not spam, that's the question</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Spam or ham</a>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Spam or ham
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>